id: devcheck
package: flar2.devcheck
display_name: "DevCheck Device & System Info"
apk_file_type: XAPK
apkpure_slug: devcheck-device-system-info-app
analysis_dir: analysis/devcheck

verify:
  apk: analysis/devcheck/extract/flar2.devcheck.apk
  assertions:
    - file: defpackage/wj.java
      pattern: 'return true;'
      label: isPro
    - file: com/pairip/SignatureCheck.java
      pattern: 'Method not decompiled: com.pairip.SignatureCheck.verifyIntegrity'
      label: bypassPairIpIntegrity
    - file: com/pairip/VMRunner.java
      pattern: 'DFQzzv4Rl5kZNZOE'
      label: bypassPairIpStartup
